# Generated by Django 4.2.2 on 2023-08-30 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kompiuteris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=80, verbose_name='Pavadinimas')),
            ],
        ),
        migrations.CreateModel(
            name='Stacionarus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kompiuteris', models.CharField(max_length=100, verbose_name='Kompiuteris')),
                ('kaina', models.IntegerField(verbose_name='Kaina')),
                ('aprasymas', models.TextField(max_length=2000, verbose_name='Aprašymas')),
                ('kompiuterisFK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stacionarus_set', to='kompiuteriai.kompiuteris')),
            ],
        ),
        migrations.CreateModel(
            name='Nesiojamas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kompiuteris', models.CharField(max_length=100, verbose_name='Kompiuteris')),
                ('kaina', models.IntegerField(verbose_name='Kaina')),
                ('aprasymas', models.TextField(max_length=2000, verbose_name='Aprašymas')),
                ('kompiuterisFK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Nesiojamas_set', to='kompiuteriai.kompiuteris')),
            ],
        ),
    ]
