# Generated by Django 4.2.2 on 2023-08-30 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kompiuteriai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nesiojamas',
            name='kompiuterisFK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nesiojamas_set', to='kompiuteriai.kompiuteris'),
        ),
    ]
